package com.example.hnotes.core.designsystem.theme

import androidx.compose.ui.graphics.Color

val theme_light_primary = Color(color = 0xFF00629F)
val theme_light_onPrimary = Color(color = 0xFFFFFFFF)
val theme_light_primaryContainer = Color(color = 0xFFD0E4FF)
val theme_light_onPrimaryContainer = Color(color = 0xFF001D34)
val theme_light_secondary = Color(color = 0xFF526070)
val theme_light_onSecondary = Color(color = 0xFFFFFFFF)
val theme_light_secondaryContainer = Color(color = 0xFFD6E4F7)
val theme_light_onSecondaryContainer = Color(color = 0xFF0F1D2A)
val theme_light_tertiary = Color(color = 0xFF695779)
val theme_light_onTertiary = Color(color = 0xFFFFFFFF)
val theme_light_tertiaryContainer = Color(color = 0xFFF0DBFF)
val theme_light_onTertiaryContainer = Color(color = 0xFF241532)
val theme_light_error = Color(color = 0xFFBA1A1A)
val theme_light_errorContainer = Color(color = 0xFFFFDAD6)
val theme_light_onError = Color(color = 0xFFFFFFFF)
val theme_light_onErrorContainer = Color(color = 0xFF410002)
val theme_light_background = Color(color = 0xFFFCFCFF)
val theme_light_onBackground = Color(color = 0xFF1A1C1E)
val theme_light_surface = Color(color = 0xFFFCFCFF)
val theme_light_onSurface = Color(color = 0xFF1A1C1E)
val theme_light_surfaceVariant = Color(color = 0xFFDEE3EB)
val theme_light_onSurfaceVariant = Color(color = 0xFF42474E)
val theme_light_outline = Color(color = 0xFF73777F)
val theme_light_inverseOnSurface = Color(color = 0xFFF1F0F4)
val theme_light_inverseSurface = Color(color = 0xFF2F3033)
val theme_light_inversePrimary = Color(color = 0xFF9BCBFF)
val theme_light_shadow = Color(color = 0xFF000000)
val theme_light_surfaceTint = Color(color = 0xFF00629F)
val theme_light_outlineVariant = Color(color = 0xFFC2C7CF)
val theme_light_scrim = Color(color = 0xFF000000)

val theme_dark_primary = Color(color = 0xFF9BCBFF)
val theme_dark_onPrimary = Color(color = 0xFF003356)
val theme_dark_primaryContainer = Color(color = 0xFF004A79)
val theme_dark_onPrimaryContainer = Color(color = 0xFFD0E4FF)
val theme_dark_secondary = Color(color = 0xFFBAC8DB)
val theme_dark_onSecondary = Color(color = 0xFF243240)
val theme_dark_secondaryContainer = Color(color = 0xFF3B4857)
val theme_dark_onSecondaryContainer = Color(color = 0xFFD6E4F7)
val theme_dark_tertiary = Color(color = 0xFFD5BEE5)
val theme_dark_onTertiary = Color(color = 0xFF3A2A48)
val theme_dark_tertiaryContainer = Color(color = 0xFF514060)
val theme_dark_onTertiaryContainer = Color(color = 0xFFF0DBFF)
val theme_dark_error = Color(color = 0xFFFFB4AB)
val theme_dark_errorContainer = Color(color = 0xFF93000A)
val theme_dark_onError = Color(color = 0xFF690005)
val theme_dark_onErrorContainer = Color(color = 0xFFFFDAD6)
val theme_dark_background = Color(color = 0xFF1A1C1E)
val theme_dark_onBackground = Color(color = 0xFFE2E2E6)
val theme_dark_surface = Color(color = 0xFF1A1C1E)
val theme_dark_onSurface = Color(color = 0xFFE2E2E6)
val theme_dark_surfaceVariant = Color(color = 0xFF42474E)
val theme_dark_onSurfaceVariant = Color(color = 0xFFC2C7CF)
val theme_dark_outline = Color(color = 0xFF8C9199)
val theme_dark_inverseOnSurface = Color(color = 0xFF1A1C1E)
val theme_dark_inverseSurface = Color(color = 0xFFE2E2E6)
val theme_dark_inversePrimary = Color(color = 0xFF00629F)
val theme_dark_shadow = Color(color = 0xFF000000)
val theme_dark_surfaceTint = Color(color = 0xFF9BCBFF)
val theme_dark_outlineVariant = Color(color = 0xFF42474E)
val theme_dark_scrim = Color(color = 0xFF000000)

val seed = Color(color = 0xFF00629F)